# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - bash: echo 'stage build. job build. step 1'
  - stage: provision
    jobs:
      - job: build
        steps:
          - bash: echo 'stage build. job build. step 1'
  - stage: dev
    jobs:
      - job: build
        steps:
          - bash: echo 'stage build. job build. step 1'
  - stage: prod
    jobs:
      - job: build
        steps:
          - bash: echo 'stage build. job build. step 1'